trigger:
  branches:
    include:
      - Dev

pr:
  branches:
    include:
      - Dev

variables:
  NODE_OPTIONS: "--max-old-space-size=6000"

# Use your self-hosted agent pool
pool:
  name: testPipeline  # This is your custom self-hosted agent pool

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '20.11.0'
    displayName: 'Install Node.js'

  - powershell: |
      # npm install -D @craco/craco
      npm install
      cd client
      npm install --legacy-peer-deps
      npm run build
    displayName: 'npm install and build client'

  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)\client\build'
      Contents: '**'
      TargetFolder: '$(Build.ArtifactStagingDirectory)\usa-dev\client\build'
    displayName: 'Copy Client Build'

  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)'
      Contents: |
        **\*
        !client\**\*
        !node_modules\**\*
        !.git\**\*
      TargetFolder: '$(Build.ArtifactStagingDirectory)\usa-dev\server'
    displayName: 'Copy Server Code'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
    condition: succeeded()
    displayName: 'Publish Artifacts'

  # Deploy to Windows VM 
  - task: WindowsMachineFileCopy@2
    inputs:
      SourcePath: '$(Pipeline.Workspace)\drop\usa-dev\client\build\*'
      MachineNames: '172.178.49.66'  # or DNS name
      AdminUserName: 'test-vm1'
      AdminPassword: 'testPassword@1'  
      TargetPath: 'C:\aerospace-digitalization-cicd'
    displayName: 'Copy Artifacts to VM'